version: '3'
services:
  proofofaccess:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - ipfshost=ipfs
      - ipfsprotocol=http
      - ipfsport=5001
    stdin_open: true
    tty: true
    networks:
      - proofofaccess
  ipfs:
    image: ipfs/kubo:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500m
    ports:
      - 5001:5001
    volumes:
      - ipfs:/data/ipfs
    networks:
      - proofofaccess
volumes:
  ipfs:
  snap:

networks:
  proofofaccess:

